In [6]:
x = [2,4,6]
y = [3,5,6]
res=list()
for xi,yi in zip(x,y):
    res.append(xi+yi)
print(res)

[5, 9, 12]


In [7]:
[xi+yi for xi,yi in zip(x,y)]

[5, 9, 12]

In [12]:
#vectores
import numpy as np #para manejar vectores y matrices
x = np.array([2,4,6])
y = np.array([3,5,6])

print(x+y) #suma
print(x-y) #resta
print(x*5) #mult. por escalar
x.dot(y), x@y #prod punto
np.linalg.norm(x) #

[ 5  9 12]
[-1 -1  0]
[10 20 30]


7.483314773547883

In [16]:
#matriz
import numpy as np

A = np.array([[1,2,3],
              [1,0,0], 
              [1,2,3]])

B = np.array([[1,0,5],
              [7,5,0], 
              [2,1,1]])
print(A+B) #suma de matrices
print(A@B)# multiplicacion de matrices

[[2 2 8]
 [8 5 0]
 [3 3 4]]
[[21 13  8]
 [ 1  0  5]
 [21 13  8]]


In [18]:
import numpy as np
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [21]:
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
""""resolver
    x-2y=1
    3x+2y=11
"""
import numpy as np
cof=np.array([[1,-2],
           [3,2]])
ind=np.array([[1],
               [11]])
x_y=np.linalg.inv(cof)@ind
print(x_y)


[[3.]
 [1.]]


In [27]:
""""resolver
    x+2y+3z=6
    2x+5y+2z=4
    6x -3y +z=2
"""
import numpy as np
cof=np.array([[1,2,3],
              [2,5,2],
              [6,-3,1]])
ind=np.array([[6],
              [4],
              [2]])
x_y=np.linalg.inv(cof)@ind
print(x_y)

#o

print(np.linalg.solve(cof,ind))

[[-1.11022302e-16]
 [-1.11022302e-16]
 [ 2.00000000e+00]]
[[0.]
 [0.]
 [2.]]


In [28]:
#La Mercedes
cof=np.array([[3,2,4],
              [5,3,2],
              [6,6,6]])
ind=np.array([[206],
              [210],
              [412]])
print(np.linalg.solve(cof,ind))

[[15.33333333]
 [26.66666667]
 [26.66666667]]


In [29]:
#La Juana
cof=np.array([[3,2,1],
              [2,1,1],
              [1,1,1]])
ind=np.array([[130],
              [90],
              [60]])
print(np.linalg.solve(cof,ind))

[[30.]
 [10.]
 [20.]]
