In [1]:
import os
import pandas as pd
import numpy as np

In [3]:
!dir

 El volumen de la unidad C es Windows
 El número de serie del volumen es: 9059-79E2

 Directorio de C:\Users\USUARIO\Robotica Industrial

30/03/2020  05:16 p. m.    <DIR>          .
30/03/2020  05:16 p. m.    <DIR>          ..
30/03/2020  05:10 p. m.    <DIR>          .ipynb_checkpoints
25/01/2020  08:12 p. m.             1,339 1 class.ipynb
26/01/2020  10:21 p. m.             2,707 1 tarea.ipynb
27/01/2020  07:27 p. m.             5,843 2 class.ipynb
10/02/2020  07:19 p. m.           416,263 3 class.ipynb
17/02/2020  08:07 p. m.            40,636 4 Class.ipynb
24/02/2020  08:10 p. m.           105,338 5 Class.ipynb
02/03/2020  06:09 p. m.           313,317 6 class.ipynb
09/03/2020  06:53 p. m.            19,682 7 class.ipynb
30/03/2020  03:40 p. m.    <DIR>          Datasets
27/01/2020  06:23 p. m.            21,843 FuncionesMod.ipynb
24/02/2020  07:03 p. m.             5,222 respuesta.xlsx
27/01/2020  08:18 p. m.             9,210 Untitled.ipynb
30/03/2020  05:16 p. m.             9,

In [4]:
dataset_path = os.path.join("Datasets","titanic3.csv")
titanic = pd.read_csv(dataset_path)
print(titanic.columns)

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')


In [5]:
titanic.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [7]:
titanic.shape

(1309, 14)

In [8]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [9]:
labels = titanic.survived.values
labels

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
features = titanic[['pclass','sex', 'age', 'sibsp', 'parch','fare','embarked']]

In [11]:
features.head()

pclass     sex      age  sibsp  parch      fare embarked
0       1  female  29.0000      0      0  211.3375        S
1       1    male   0.9167      1      2  151.5500        S
2       1  female   2.0000      1      2  151.5500        S
3       1    male  30.0000      1      2  151.5500        S
4       1  female  25.0000      1      2  151.5500        S

In [12]:
pd.get_dummies(features).head()

pclass      age  sibsp  parch      fare  sex_female  sex_male  embarked_C  \
0       1  29.0000      0      0  211.3375           1         0           0   
1       1   0.9167      1      2  151.5500           0         1           0   
2       1   2.0000      1      2  151.5500           1         0           0   
3       1  30.0000      1      2  151.5500           0         1           0   
4       1  25.0000      1      2  151.5500           1         0           0   

   embarked_Q  embarked_S  
0           0           1  
1           0           1  
2           0           1  
3           0           1  
4           0           1

In [14]:
features_dummies = pd.get_dummies(features, columns=['pclass','sex','embarked'])
features_dummies.head()

age  sibsp  parch      fare  pclass_1  pclass_2  pclass_3  sex_female  \
0  29.0000      0      0  211.3375         1         0         0           1   
1   0.9167      1      2  151.5500         1         0         0           0   
2   2.0000      1      2  151.5500         1         0         0           1   
3  30.0000      1      2  151.5500         1         0         0           0   
4  25.0000      1      2  151.5500         1         0         0           1   

   sex_male  embarked_C  embarked_Q  embarked_S  
0         0           0           0           1  
1         1           0           0           1  
2         0           0           0           1  
3         1           0           0           1  
4         0           0           0           1

In [15]:
features_dummies.shape

(1309, 12)

In [16]:
features_dummies.isna().any()

age            True
sibsp         False
parch         False
fare           True
pclass_1      False
pclass_2      False
pclass_3      False
sex_female    False
sex_male      False
embarked_C    False
embarked_Q    False
embarked_S    False
dtype: bool

In [20]:
features_dummies_train= features_dummies.dropna()
features_dummies_train.isna().any

<bound method DataFrame.any of         age  sibsp  parch   fare  pclass_1  pclass_2  pclass_3  sex_female  \
0     False  False  False  False     False     False     False       False   
1     False  False  False  False     False     False     False       False   
2     False  False  False  False     False     False     False       False   
3     False  False  False  False     False     False     False       False   
4     False  False  False  False     False     False     False       False   
...     ...    ...    ...    ...       ...       ...       ...         ...   
1301  False  False  False  False     False     False     False       False   
1304  False  False  False  False     False     False     False       False   
1306  False  False  False  False     False     False     False       False   
1307  False  False  False  False     False     False     False       False   
1308  False  False  False  False     False     False     False       False   

      sex_male  embarked_C  emba

In [21]:
features_dummies_train.shape

(1045, 12)

In [22]:
labels_train = labels[features_dummies_train.index]
labels_train

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

# Logistic Regresion

In [23]:
from sklearn.linear_model import LogisticRegression

In [25]:
LogisticRegression?

In [26]:
model= LogisticRegression(solver ='lbfgs', max_iter=500)

In [27]:
model.fit(features_dummies_train, labels_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
labels_train #real

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
model.predict(features_dummies_train)#predict

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [31]:
sum(model.predict(features_dummies_train) == labels_train)

828

In [37]:
sum(model.predict(features_dummies_train) == labels_train)/(len(labels_train))

0.7923444976076555

In [38]:
len(labels_train)

1045

In [39]:
828/1045

0.7923444976076555

In [40]:
print("Logistic regressio score: ", model.score(features_dummies_train, labels_train))

Logistic regressio score:  0.7923444976076555


In [41]:
from sklearn.model_selection import train_test_split

In [43]:
train_data, test_data, train_labels, test_labels = train_test_split(features_dummies_train, labels_train, random_state=0,test_size=0.33)

In [44]:
train_data.shape, test_data.shape

((700, 12), (345, 12))

In [45]:
train_labels.shape,test_labels.shape

((700,), (345,))

In [48]:
model = LogisticRegression(solver='lbfgs', max_iter=500).fit(train_data, train_labels)
print("Logistic regressio score: %f "% model.score(test_data, test_labels))

Logistic regressio score: 0.788406 


In [ ]:
[1, 'female', 29.0,0,0,211.3375]